/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Body} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Back Glass']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane_5.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane_6.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane_7.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Buttons.geometry} material={materials.Body} position={[-0.965, -0.101, -0.71]} rotation={[0, 0, -Math.PI / 2]} />
        <group position={[-0.497, 0.024, -1.577]} scale={0.378}>
          <mesh geometry={nodes.Plane011.geometry} material={materials['Back Glass']} />
          <mesh geometry={nodes.Plane011_1.geometry} material={materials.Body} />
          <mesh geometry={nodes.Plane011_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane011_3.geometry} material={materials['Material.007']} />
          <group position={[-0.421, -0.064, -0.42]} scale={[0.136, 0.07, 0.136]}>
            <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Icosphere001_1.geometry} material={materials.Body} />
            <mesh geometry={nodes.Icosphere001_2.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Icosphere001_3.geometry} material={materials.Glass} />
            <mesh geometry={nodes.Icosphere001_4.geometry} material={materials['Material.005']} />
          </group>
        </group>
        <group position={[0.249, -0.188, -1.953]} scale={[0.019, 0.009, 0.019]}>
          <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Icosphere_1.geometry} material={materials['Material.005']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
